\c :database_name
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM :user_name;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM :user_name;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM :user_name;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM :user_name;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM :user_name;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM :user_name;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM :user_name;
REVOKE CONNECT ON DATABASE :database_name FROM :user_name;


\c postgres
DROP DATABASE IF EXISTS :database_name;
DROP USER IF EXISTS :user_name;
